# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_dualchannel_system/zynq_dualchannel_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system || ORIG_REF_NAME==zynq_dualchannel_system} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_axi_gpio_0_0/zynq_dualchannel_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_axi_gpio_0_0 || ORIG_REF_NAME==zynq_dualchannel_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_axi_gpio_1_0/zynq_dualchannel_system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_axi_gpio_1_0 || ORIG_REF_NAME==zynq_dualchannel_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_processing_system7_0_0/zynq_dualchannel_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_dualchannel_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_xbar_0/zynq_dualchannel_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_xbar_0 || ORIG_REF_NAME==zynq_dualchannel_system_xbar_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_ps7_0_axi_periph_0/zynq_dualchannel_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_dualchannel_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_rst_ps7_0_100M_0/zynq_dualchannel_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_dualchannel_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_auto_pc_0/zynq_dualchannel_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_dualchannel_system_auto_pc_0 || ORIG_REF_NAME==zynq_dualchannel_system_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq_dualchannel_system/zynq_dualchannel_system_ooc.xdc
