# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Zynq_Book/rtos_task_management/rtos_task_management.srcs/sources_1/bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_processing_system7_0_0/zynq_dualchannel_system_processing_system7_0_0.xci
# IP: The module: 'zynq_dualchannel_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/rtos_task_management/rtos_task_management.srcs/sources_1/bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_processing_system7_0_0/zynq_dualchannel_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_dualchannel_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Zynq_Book/rtos_task_management/rtos_task_management.srcs/sources_1/bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_processing_system7_0_0/zynq_dualchannel_system_processing_system7_0_0.xci
# IP: The module: 'zynq_dualchannel_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/rtos_task_management/rtos_task_management.srcs/sources_1/bd/zynq_dualchannel_system/ip/zynq_dualchannel_system_processing_system7_0_0/zynq_dualchannel_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_dualchannel_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
